### ISSUE TITLE
[FEATURE] Sync version?

### ISSUE THREAD

**Issue by amatiasq** [speed-highlight/core#28] opened 2022-07-04 14:32 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by matubu** [comment] 2022-07-04 15:28
Duplicate of #29

**Closed by matubu** 2022-07-04 15:28 UTC
Labels: enhancement

**Comment by amatiasq** [comment] 2022-07-04 21:18
Did I create two issues? sorry 🙈
